name: First Action Practice

# 1. Event: 언제 실행할 것인가?
on: [push] 

# 2. Jobs: 어떤 작업들을 할 것인가?
jobs:
  say-hello-job:
    # 3. Runner: 어떤 환경(서버)에서 실행할 것인가?
    runs-on: ubuntu-latest 

    # 4. Steps: 순서대로 어떤 명령을 내릴 것인가?
    steps:
      - name: 첫 번째 인사말 출력
        run: echo "안녕하세요! 첫 번째 GitHub Action이 성공적으로 실행되었습니다."
